FROM node:22-alpine AS dev

WORKDIR /app

COPY frontend/package.json package-lock.json* ./

RUN npm install

COPY frontend . 

ARG FRONTEND_PORT
EXPOSE $FRONTEND_PORT

ENV NODE_ENV=development

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]